class CarModel {
  final String name;
  final String url;
  final String difficulty;

  CarModel(this.name, this.url, this.difficulty);

  static List<CarModel> allCars = [
    CarModel(
      "9ff",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/9ff.png",
      "hard",
    ),
    CarModel(
      "Abadal",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/abadal.png",
      "hard",
    ),
    CarModel(
      "Abarth",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/abarth.png",
      "hard",
    ),
    CarModel(
      "Abbott-Detroit",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/abbott-detroit.png",
      "hard",
    ),
    CarModel(
      "ABT",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/abt.png",
      "hard",
    ),
    CarModel(
      "AC",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ac.png",
      "hard",
    ),
    CarModel(
      "Acura",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/acura.png",
      "easy",
    ),
    CarModel(
      "Aiways",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/aiways.png",
      "hard",
    ),
    CarModel(
      "Aixam",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/aixam.png",
      "hard",
    ),
    CarModel(
      "Alfa Romeo",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/alfa-romeo.png",
      "easy",
    ),
    CarModel(
      "Alpina",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/alpina.png",
      "hard",
    ),
    CarModel(
      "Alpine",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/alpine.png",
      "hard",
    ),
    CarModel(
      "Alta",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/alta.png",
      "hard",
    ),
    CarModel(
      "Alvis",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/alvis.png",
      "hard",
    ),
    CarModel(
      "AMC",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/amc.png",
      "hard",
    ),
    CarModel(
      "Apollo",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/apollo.png",
      "hard",
    ),
    CarModel(
      "Arash",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/arash.png",
      "hard",
    ),
    CarModel(
      "Arcfox",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/arcfox.png",
      "hard",
    ),
    CarModel(
      "Ariel",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ariel.png",
      "easy",
    ),
    CarModel(
      "ARO",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/aro.png",
      "hard",
    ),
    CarModel(
      "Arrinera",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/arrinera.png",
      "hard",
    ),
    CarModel(
      "Arrival",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/arrival.png",
      "hard",
    ),
    CarModel(
      "Artega",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/artega.png",
      "hard",
    ),
    CarModel(
      "Ascari",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ascari.png",
      "hard",
    ),
    CarModel(
      "Askam",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/askam.png",
      "hard",
    ),
    CarModel(
      "Aspark",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/aspark.png",
      "hard",
    ),
    CarModel(
      "Aston Martin",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/aston-martin.png",
      "easy",
    ),
    CarModel(
      "Atalanta",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/atalanta.png",
      "hard",
    ),
    CarModel(
      "Auburn",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/auburn.png",
      "hard",
    ),
    CarModel(
      "Audi",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/audi.png",
      "easy",
    ),
    CarModel(
      "Audi Sport",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/audi-sport.png",
      "hard",
    ),
    CarModel(
      "Austin",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/austin.png",
      "hard",
    ),
    CarModel(
      "Autobacs",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/autobacs.png",
      "hard",
    ),
    CarModel(
      "Autobianchi",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/autobianchi.png",
      "hard",
    ),
    CarModel(
      "Axon",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/axon.png",
      "hard",
    ),
    CarModel(
      "BAC",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bac.png",
      "hard",
    ),
    CarModel(
      "BAIC Motor",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/baic-motor.png",
      "medium",
    ),
    CarModel(
      "Baojun",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/baojun.png",
      "medium",
    ),
    CarModel(
      "BeiBen",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/beiben.png",
      "hard",
    ),
    CarModel(
      "Bentley",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bentley.png",
      "easy",
    ),
    CarModel(
      "Berkeley",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/berkeley.png",
      "hard",
    ),
    CarModel(
      "Berliet",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/berliet.png",
      "hard",
    ),
    CarModel(
      "Bertone",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bertone.png",
      "hard",
    ),
    CarModel(
      "Bestune",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bestune.png",
      "medium",
    ),
    CarModel(
      "BharatBenz",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bharatbenz.png",
      "medium",
    ),
    CarModel(
      "Bitter",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bitter.png",
      "hard",
    ),
    CarModel(
      "Bizzarrini",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bizzarrini.png",
      "hard",
    ),
    CarModel(
      "BMW",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bmw.png",
      "easy",
    ),
    CarModel(
      "BMW M",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bmw-m.png",
      "hard",
    ),
    CarModel(
      "Borgward",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/borgward.png",
      "hard",
    ),
    CarModel(
      "Bowler",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bowler.png",
      "hard",
    ),
    CarModel(
      "Brabus",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/brabus.png",
      "hard",
    ),
    CarModel(
      "Brammo",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/brammo.png",
      "hard",
    ),
    CarModel(
      "Brilliance",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/brilliance.png",
      "medium",
    ),
    CarModel(
      "Bristol",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bristol.png",
      "hard",
    ),
    CarModel(
      "Brooke",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/brooke.png",
      "hard",
    ),
    CarModel(
      "Bufori",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bufori.png",
      "hard",
    ),
    CarModel(
      "Bugatti",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bugatti.png",
      "easy",
    ),
    CarModel(
      "Buick",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/buick.png",
      "easy",
    ),
    CarModel(
      "BYD",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/byd.png",
      "easy",
    ),
    CarModel(
      "Byton",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/byton.png",
      "hard",
    ),
    CarModel(
      "Cadillac",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/cadillac.png",
      "easy",
    ),
    CarModel(
      "CAMC",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/camc.png",
      "hard",
    ),
    CarModel(
      "Canoo",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/canoo.png",
      "hard",
    ),
    CarModel(
      "Caparo",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/caparo.png",
      "hard",
    ),
    CarModel(
      "Carlsson",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/carlsson.png",
      "hard",
    ),
    CarModel(
      "Caterham",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/caterham.png",
      "easy",
    ),
    CarModel(
      "Changan",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/changan.png",
      "medium",
    ),
    CarModel(
      "Changfeng",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/changfeng.png",
      "medium",
    ),
    CarModel(
      "Chery",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/chery.png",
      "medium",
    ),
    CarModel(
      "Chevrolet",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/chevrolet.png",
      "easy",
    ),
    CarModel(
      "Chevrolet Corvette",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/chevrolet-corvette.png",
      "hard",
    ),
    CarModel(
      "Chrysler",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/chrysler.png",
      "easy",
    ),
    CarModel(
      "Cisitalia",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/cisitalia.png",
      "hard",
    ),
    CarModel(
      "Citroën",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/citroen.png",
      "hard",
    ),
    CarModel(
      "Cizeta",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/cizeta.png",
      "hard",
    ),
    CarModel(
      "Cole",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/cole.png",
      "hard",
    ),
    CarModel(
      "Corre La Licorne",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/corre-la-licorne.png",
      "hard",
    ),
    CarModel(
      "Dacia",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dacia.png",
      "easy",
    ),
    CarModel(
      "Daewoo",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/daewoo.png",
      "easy",
    ),
    CarModel(
      "DAF",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/daf.png",
      "medium",
    ),
    CarModel(
      "Daihatsu",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/daihatsu.png",
      "hard",
    ),
    CarModel(
      "Daimler",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/daimler.png",
      "hard",
    ),
    CarModel(
      "Dartz",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dartz.png",
      "hard",
    ),
    CarModel(
      "Datsun",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/datsun.png",
      "hard",
    ),
    CarModel(
      "David Brown",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/david-brown.png",
      "hard",
    ),
    CarModel(
      "Dayun",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dayun.png",
      "hard",
    ),
    CarModel(
      "De Tomaso",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/de-tomaso.png",
      "easy",
    ),
    CarModel(
      "Delage",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/delage.png",
      "hard",
    ),
    CarModel(
      "DeSoto",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/desoto.png",
      "hard",
    ),
    CarModel(
      "Detroit Electric",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/detroit-electric.png",
      "hard",
    ),
    CarModel(
      "Devel Sixteen",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/devel-sixteen.png",
      "hard",
    ),
    CarModel(
      "Diatto",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/diatto.png",
      "hard",
    ),
    CarModel(
      "DINA",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dina.png",
      "hard",
    ),
    CarModel(
      "DKW",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dkw.png",
      "hard",
    ),
    CarModel(
      "DMC",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dmc.png",
      "hard",
    ),
    CarModel(
      "Dodge",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dodge.png",
      "easy",
    ),
    CarModel(
      "Dodge Viper",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dodge-viper.png",
      "hard",
    ),
    CarModel(
      "Dongfeng",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dongfeng.png",
      "medium",
    ),
    CarModel(
      "Donkervoort",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/donkervoort.png",
      "hard",
    ),
    CarModel(
      "Drako",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/drako.png",
      "hard",
    ),
    CarModel(
      "DS",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ds.png",
      "hard",
    ),
    CarModel(
      "Duesenberg",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/duesenberg.png",
      "hard",
    ),
    CarModel(
      "Eagle",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/eagle.png",
      "hard",
    ),
    CarModel(
      "EDAG",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/edag.png",
      "hard",
    ),
    CarModel(
      "Edsel",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/edsel.png",
      "hard",
    ),
    CarModel(
      "Eicher",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/eicher.png",
      "medium",
    ),
    CarModel(
      "Elemental",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/elemental.png",
      "hard",
    ),
    CarModel(
      "Elfin",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/elfin.png",
      "hard",
    ),
    CarModel(
      "Elva",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/elva.png",
      "hard",
    ),
    CarModel(
      "Englon",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/englon.png",
      "hard",
    ),
    CarModel(
      "ERF",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/erf.png",
      "hard",
    ),
    CarModel(
      "Eterniti",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/eterniti.png",
      "hard",
    ),
    CarModel(
      "Exeed",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/exeed.png",
      "hard",
    ),
    CarModel(
      "Facel Vega",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/facel-vega.png",
      "hard",
    ),
    CarModel(
      "Faraday Future",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/faraday-future.png",
      "hard",
    ),
    CarModel(
      "FAW",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/faw.png",
      "medium",
    ),
    CarModel(
      "FAW Jiefang",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/faw-jiefang.png",
      "hard",
    ),
    CarModel(
      "Ferrari",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ferrari.png",
      "easy",
    ),
    CarModel(
      "Fiat",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/fiat.png",
      "easy",
    ),
    CarModel(
      "Fioravanti",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/fioravanti.png",
      "hard",
    ),
    CarModel(
      "Fisker",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/fisker.png",
      "easy",
    ),
    CarModel(
      "Foden",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/foden.png",
      "hard",
    ),
    CarModel(
      "Force Motors",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/force-motors.png",
      "medium",
    ),
    CarModel(
      "Ford",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ford.png",
      "easy",
    ),
    CarModel(
      "Ford Mustang",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ford-mustang.png",
      "hard",
    ),
    CarModel(
      "Foton",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/foton.png",
      "medium",
    ),
    CarModel(
      "FPV",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/fpv.png",
      "hard",
    ),
    CarModel(
      "Franklin",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/franklin.png",
      "hard",
    ),
    CarModel(
      "Freightliner",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/freightliner.png",
      "medium",
    ),
    CarModel(
      "FSO",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/fso.png",
      "hard",
    ),
    CarModel(
      "GAC Group",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gac-group.png",
      "medium",
    ),
    CarModel(
      "Gardner Douglas",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gardner-douglas.png",
      "hard",
    ),
    CarModel(
      "GAZ",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gaz.png",
      "hard",
    ),
    CarModel(
      "Geely",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/geely.png",
      "easy",
    ),
    CarModel(
      "General Motors",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/general-motors.png",
      "hard",
    ),
    CarModel(
      "Genesis",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/genesis.png",
      "easy",
    ),
    CarModel(
      "Geo",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/geo.png",
      "hard",
    ),
    CarModel(
      "Geometry",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/geometry.png",
      "medium",
    ),
    CarModel(
      "Gilbern",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gilbern.png",
      "hard",
    ),
    CarModel(
      "Gillet",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gillet.png",
      "hard",
    ),
    CarModel(
      "Ginetta",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ginetta.png",
      "hard",
    ),
    CarModel(
      "GMC",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gmc.png",
      "easy",
    ),
    CarModel(
      "Golden Dragon",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/golden-dragon.png",
      "hard",
    ),
    CarModel(
      "Gonow",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gonow.png",
      "medium",
    ),
    CarModel(
      "Great Wall",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/great-wall.png",
      "medium",
    ),
    CarModel(
      "Grinnall",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/grinnall.png",
      "hard",
    ),
    CarModel(
      "Gumpert",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gumpert.png",
      "hard",
    ),
    CarModel(
      "Hafei",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hafei.png",
      "medium",
    ),
    CarModel(
      "Haima",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/haima.png",
      "medium",
    ),
    CarModel(
      "Haval",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/haval.png",
      "medium",
    ),
    CarModel(
      "Hawtai",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hawtai.png",
      "hard",
    ),
    CarModel(
      "Hennessey",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hennessey.png",
      "hard",
    ),
    CarModel(
      "Higer",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/higer.png",
      "hard",
    ),
    CarModel(
      "Hillman",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hillman.png",
      "hard",
    ),
    CarModel(
      "Hindustan Motors",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hindustan-motors.png",
      "hard",
    ),
    CarModel(
      "Hino",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hino.png",
      "medium",
    ),
    CarModel(
      "HiPhi",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hiphi.png",
      "hard",
    ),
    CarModel(
      "Hispano-Suiza",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hispano-suiza.png",
      "hard",
    ),
    CarModel(
      "Holden",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/holden.png",
      "hard",
    ),
    CarModel(
      "Hommell",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hommell.png",
      "hard",
    ),
    CarModel(
      "Honda",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/honda.png",
      "easy",
    ),
    CarModel(
      "Hongqi",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hongqi.png",
      "medium",
    ),
    CarModel(
      "Hongyan",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hongyan.png",
      "hard",
    ),
    CarModel(
      "Horch",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/horch.png",
      "hard",
    ),
    CarModel(
      "HSV",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hsv.png",
      "hard",
    ),
    CarModel(
      "Hudson",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hudson.png",
      "hard",
    ),
    CarModel(
      "Hummer",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hummer.png",
      "easy",
    ),
    CarModel(
      "Hupmobile",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hupmobile.png",
      "hard",
    ),
    CarModel(
      "Hyundai",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hyundai.png",
      "easy",
    ),
    CarModel(
      "IC Bus",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ic-bus.png",
      "hard",
    ),
    CarModel(
      "IH",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ih.png",
      "hard",
    ),
    CarModel(
      "IKCO",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ikco.png",
      "hard",
    ),
    CarModel(
      "Infiniti",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/infiniti.png",
      "easy",
    ),
    CarModel(
      "Innocenti",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/innocenti.png",
      "hard",
    ),
    CarModel(
      "Intermeccanica",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/intermeccanica.png",
      "hard",
    ),
    CarModel(
      "International",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/international.png",
      "medium",
    ),
    CarModel(
      "Irizar",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/irizar.png",
      "hard",
    ),
    CarModel(
      "Isdera",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/isdera.png",
      "hard",
    ),
    CarModel(
      "Iso",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/iso.png",
      "hard",
    ),
    CarModel(
      "Isuzu",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/isuzu.png",
      "easy",
    ),
    CarModel(
      "Iveco",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/iveco.png",
      "medium",
    ),
    CarModel(
      "JAC",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jac.png",
      "medium",
    ),
    CarModel(
      "Jaguar",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jaguar.png",
      "easy",
    ),
    CarModel(
      "Jawa",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jawa.png",
      "hard",
    ),
    CarModel(
      "JBA Motors",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jba-motors.png",
      "hard",
    ),
    CarModel(
      "Jeep",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jeep.png",
      "easy",
    ),
    CarModel(
      "Jensen",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jensen.png",
      "hard",
    ),
    CarModel(
      "Jetta",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jetta.png",
      "hard",
    ),
    CarModel(
      "JMC",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jmc.png",
      "medium",
    ),
    CarModel(
      "Kaiser",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/kaiser.png",
      "hard",
    ),
    CarModel(
      "Kamaz",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/kamaz.png",
      "hard",
    ),
    CarModel(
      "Karlmann King",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/karlmann-king.png",
      "hard",
    ),
    CarModel(
      "Karma",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/karma.png",
      "easy",
    ),
    CarModel(
      "Keating",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/keating.png",
      "hard",
    ),
    CarModel(
      "Kenworth",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/kenworth.png",
      "medium",
    ),
    CarModel(
      "Kia",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/kia.png",
      "easy",
    ),
    CarModel(
      "King Long",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/king-long.png",
      "hard",
    ),
    CarModel(
      "Koenigsegg",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/koenigsegg.png",
      "easy",
    ),
    CarModel(
      "KTM",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ktm.png",
      "easy",
    ),
    CarModel(
      "Lada",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lada.png",
      "hard",
    ),
    CarModel(
      "Lagonda",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lagonda.png",
      "hard",
    ),
    CarModel(
      "Lamborghini",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lamborghini.png",
      "easy",
    ),
    CarModel(
      "Lancia",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lancia.png",
      "easy",
    ),
    CarModel(
      "Land Rover",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/land-rover.png",
      "easy",
    ),
    CarModel(
      "Landwind",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/landwind.png",
      "medium",
    ),
    CarModel(
      "Laraki",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/laraki.png",
      "hard",
    ),
    CarModel(
      "Leapmotor",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/leapmotor.png",
      "hard",
    ),
    CarModel(
      "LEVC",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/levc.png",
      "medium",
    ),
    CarModel(
      "Lexus",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lexus.png",
      "easy",
    ),
    CarModel(
      "Leyland",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/leyland.png",
      "hard",
    ),
    CarModel(
      "Li Auto",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/li-auto.png",
      "easy",
    ),
    CarModel(
      "Lifan",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lifan.png",
      "medium",
    ),
    CarModel(
      "Ligier",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ligier.png",
      "hard",
    ),
    CarModel(
      "Lincoln",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lincoln.png",
      "easy",
    ),
    CarModel(
      "Lister",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lister.png",
      "hard",
    ),
    CarModel(
      "Lloyd",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lloyd.png",
      "hard",
    ),
    CarModel(
      "Lobini",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lobini.png",
      "hard",
    ),
    CarModel(
      "Lordstown",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lordstown.png",
      "hard",
    ),
    CarModel(
      "Lotus",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lotus.png",
      "easy",
    ),
    CarModel(
      "Lucid",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lucid.png",
      "easy",
    ),
    CarModel(
      "Luxgen",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/luxgen.png",
      "hard",
    ),
    CarModel(
      "Lynk & Co",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lynk-and-co.png",
      "medium",
    ),
    CarModel(
      "Mack",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mack.png",
      "medium",
    ),
    CarModel(
      "Mahindra",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mahindra.png",
      "easy",
    ),
    CarModel(
      "MAN",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/man.png",
      "medium",
    ),
    CarModel(
      "Mansory",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mansory.png",
      "hard",
    ),
    CarModel(
      "Marcos",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/marcos.png",
      "hard",
    ),
    CarModel(
      "Marlin",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/marlin.png",
      "hard",
    ),
    CarModel(
      "Maserati",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/maserati.png",
      "easy",
    ),
    CarModel(
      "Mastretta",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mastretta.png",
      "hard",
    ),
    CarModel(
      "Maxus",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/maxus.png",
      "medium",
    ),
    CarModel(
      "Maybach",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/maybach.png",
      "hard",
    ),
    CarModel(
      "MAZ",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/maz.png",
      "hard",
    ),
    CarModel(
      "Mazda",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mazda.png",
      "easy",
    ),
    CarModel(
      "Mazzanti",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mazzanti.png",
      "hard",
    ),
    CarModel(
      "McLaren",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mclaren.png",
      "easy",
    ),
    CarModel(
      "Melkus",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/melkus.png",
      "hard",
    ),
    CarModel(
      "Mercedes-AMG",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mercedes-amg.png",
      "hard",
    ),
    CarModel(
      "Mercedes-Benz",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mercedes-benz.png",
      "hard",
    ),
    CarModel(
      "Mercury",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mercury.png",
      "easy",
    ),
    CarModel(
      "Merkur",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/merkur.png",
      "hard",
    ),
    CarModel(
      "MEV",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mev.png",
      "hard",
    ),
    CarModel(
      "MG",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mg.png",
      "medium",
    ),
    CarModel(
      "Microcar",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/microcar.png",
      "hard",
    ),
    CarModel(
      "Mini",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mini.png",
      "easy",
    ),
    CarModel(
      "Mitsubishi",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mitsubishi.png",
      "easy",
    ),
    CarModel(
      "Mitsuoka",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mitsuoka.png",
      "hard",
    ),
    CarModel(
      "MK",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mk.png",
      "hard",
    ),
    CarModel(
      "Morgan",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/morgan.png",
      "easy",
    ),
    CarModel(
      "Morris",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/morris.png",
      "hard",
    ),
    CarModel(
      "Mosler",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mosler.png",
      "hard",
    ),
    CarModel(
      "Navistar",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/navistar.png",
      "medium",
    ),
    CarModel(
      "NEVS",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/nevs.png",
      "medium",
    ),
    CarModel(
      "Nikola",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/nikola.png",
      "hard",
    ),
    CarModel(
      "NIO",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/nio.png",
      "easy",
    ),
    CarModel(
      "Nissan",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/nissan.png",
      "easy",
    ),
    CarModel(
      "Nissan GT-R",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/nissan-gt-r.png",
      "hard",
    ),
    CarModel(
      "Nissan Nismo",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/nissan-nismo.png",
      "hard",
    ),
    CarModel(
      "Noble",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/noble.png",
      "easy",
    ),
    CarModel(
      "Oldsmobile",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/oldsmobile.png",
      "easy",
    ),
    CarModel(
      "Oltcit",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/oltcit.png",
      "hard",
    ),
    CarModel(
      "Opel",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/opel.png",
      "easy",
    ),
    CarModel(
      "OSCA",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/osca.png",
      "hard",
    ),
    CarModel(
      "Paccar",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/paccar.png",
      "medium",
    ),
    CarModel(
      "Packard",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/packard.png",
      "hard",
    ),
    CarModel(
      "Pagani",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/pagani.png",
      "easy",
    ),
    CarModel(
      "Panhard",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/panhard.png",
      "hard",
    ),
    CarModel(
      "Panoz",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/panoz.png",
      "hard",
    ),
    CarModel(
      "Pegaso",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/pegaso.png",
      "hard",
    ),
    CarModel(
      "Perodua",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/perodua.png",
      "easy",
    ),
    CarModel(
      "Peterbilt",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/peterbilt.png",
      "medium",
    ),
    CarModel(
      "Peugeot",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/peugeot.png",
      "easy",
    ),
    CarModel(
      "PGO",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/pgo.png",
      "hard",
    ),
    CarModel(
      "Pierce-Arrow",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/pierce-arrow.png",
      "hard",
    ),
    CarModel(
      "Pininfarina",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/pininfarina.png",
      "easy",
    ),
    CarModel(
      "Plymouth",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/plymouth.png",
      "hard",
    ),
    CarModel(
      "Polestar",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/polestar.png",
      "easy",
    ),
    CarModel(
      "Pontiac",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/pontiac.png",
      "easy",
    ),
    CarModel(
      "Porsche",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/porsche.png",
      "easy",
    ),
    CarModel(
      "Praga",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/praga.png",
      "hard",
    ),
    CarModel(
      "Premier",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/premier.png",
      "hard",
    ),
    CarModel(
      "Prodrive",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/prodrive.png",
      "hard",
    ),
    CarModel(
      "Proton",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/proton.png",
      "easy",
    ),
    CarModel(
      "Qoros",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/qoros.png",
      "hard",
    ),
    CarModel(
      "Radical",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/radical.png",
      "hard",
    ),
    CarModel(
      "RAM",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ram.png",
      "hard",
    ),
    CarModel(
      "Rambler",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rambler.png",
      "hard",
    ),
    CarModel(
      "Ranz",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ranz.png",
      "hard",
    ),
    CarModel(
      "Renault",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/renault.png",
      "easy",
    ),
    CarModel(
      "Renault Samsung",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/renault-samsung.png",
      "hard",
    ),
    CarModel(
      "Rezvani",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rezvani.png",
      "hard",
    ),
    CarModel(
      "Riley",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/riley.png",
      "hard",
    ),
    CarModel(
      "Rimac",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rimac.png",
      "easy",
    ),
    CarModel(
      "Rinspeed",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rinspeed.png",
      "hard",
    ),
    CarModel(
      "Rivian",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rivian.png",
      "easy",
    ),
    CarModel(
      "Roewe",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/roewe.png",
      "medium",
    ),
    CarModel(
      "Rolls-Royce",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rolls-royce.png",
      "easy",
    ),
    CarModel(
      "Ronart",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ronart.png",
      "hard",
    ),
    CarModel(
      "Rossion",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rossion.png",
      "hard",
    ),
    CarModel(
      "Rover",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rover.png",
      "hard",
    ),
    CarModel(
      "RUF",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ruf.png",
      "hard",
    ),
    CarModel(
      "Saab",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/saab.png",
      "easy",
    ),
    CarModel(
      "SAIC Motor",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/saic-motor.png",
      "medium",
    ),
    CarModel(
      "Saipa",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/saipa.png",
      "hard",
    ),
    CarModel(
      "Saleen",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/saleen.png",
      "hard",
    ),
    CarModel(
      "Saturn",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/saturn.png",
      "easy",
    ),
    CarModel(
      "Scania",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/scania.png",
      "medium",
    ),
    CarModel(
      "Scion",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/scion.png",
      "hard",
    ),
    CarModel(
      "SEAT",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/seat.png",
      "easy",
    ),
    CarModel(
      "Setra",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/setra.png",
      "hard",
    ),
    CarModel(
      "Shacman",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/shacman.png",
      "hard",
    ),
    CarModel(
      "Simca",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/simca.png",
      "hard",
    ),
    CarModel(
      "Singer",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/singer.png",
      "hard",
    ),
    CarModel(
      "Singulato",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/singulato.png",
      "hard",
    ),
    CarModel(
      "Sinotruk",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/sinotruk.png",
      "hard",
    ),
    CarModel(
      "Sisu",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/sisu.png",
      "hard",
    ),
    CarModel(
      "Škoda",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/skoda.png",
      "hard",
    ),
    CarModel(
      "Smart",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/smart.png",
      "easy",
    ),
    CarModel(
      "Soueast",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/soueast.png",
      "medium",
    ),
    CarModel(
      "Spania GTA",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/spania-gta.png",
      "hard",
    ),
    CarModel(
      "Spirra",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/spirra.png",
      "hard",
    ),
    CarModel(
      "Spyker",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/spyker.png",
      "hard",
    ),
    CarModel(
      "SsangYong",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ssangyong.png",
      "easy",
    ),
    CarModel(
      "SSC",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ssc.png",
      "hard",
    ),
    CarModel(
      "Sterling",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/sterling.png",
      "hard",
    ),
    CarModel(
      "Studebaker",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/studebaker.png",
      "hard",
    ),
    CarModel(
      "Stutz",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/stutz.png",
      "hard",
    ),
    CarModel(
      "Subaru",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/subaru.png",
      "easy",
    ),
    CarModel(
      "Suffolk",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/suffolk.png",
      "hard",
    ),
    CarModel(
      "Suzuki",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/suzuki.png",
      "easy",
    ),
    CarModel(
      "Talbot",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/talbot.png",
      "hard",
    ),
    CarModel(
      "Tata",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/tata.png",
      "easy",
    ),
    CarModel(
      "Tatra",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/tatra.png",
      "hard",
    ),
    CarModel(
      "Tauro",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/tauro.png",
      "hard",
    ),
    CarModel(
      "TechArt",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/techart.png",
      "hard",
    ),
    CarModel(
      "Tesla",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/tesla.png",
      "easy",
    ),
    CarModel(
      "Toyota",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/toyota.png",
      "easy",
    ),
    CarModel(
      "Toyota Alphard",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/toyota-alphard.png",
      "hard",
    ),
    CarModel(
      "Toyota Century",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/toyota-century.png",
      "hard",
    ),
    CarModel(
      "Toyota Crown",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/toyota-crown.png",
      "hard",
    ),
    CarModel(
      "Tramontana",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/tramontana.png",
      "hard",
    ),
    CarModel(
      "Trion",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/trion.png",
      "hard",
    ),
    CarModel(
      "Triumph",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/triumph.png",
      "easy",
    ),
    CarModel(
      "Troller",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/troller.png",
      "hard",
    ),
    CarModel(
      "Tucker",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/tucker.png",
      "hard",
    ),
    CarModel(
      "TVR",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/tvr.png",
      "easy",
    ),
    CarModel(
      "UAZ",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/uaz.png",
      "hard",
    ),
    CarModel(
      "UD",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ud.png",
      "hard",
    ),
    CarModel(
      "Ultima",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ultima.png",
      "hard",
    ),
    CarModel(
      "Vandenbrink",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/vandenbrink.png",
      "hard",
    ),
    CarModel(
      "Vauxhall",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/vauxhall.png",
      "hard",
    ),
    CarModel(
      "Vector",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/vector.png",
      "hard",
    ),
    CarModel(
      "Vencer",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/vencer.png",
      "hard",
    ),
    CarModel(
      "Venturi",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/venturi.png",
      "hard",
    ),
    CarModel(
      "Venucia",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/venucia.png",
      "hard",
    ),
    CarModel(
      "VinFast",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/vinfast.png",
      "hard",
    ),
    CarModel(
      "VLF",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/vlf.png",
      "hard",
    ),
    CarModel(
      "Volkswagen",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/volkswagen.png",
      "easy",
    ),
    CarModel(
      "Volvo",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/volvo.png",
      "easy",
    ),
    CarModel(
      "W Motors",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/w-motors.png",
      "hard",
    ),
    CarModel(
      "Wanderer",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/wanderer.png",
      "hard",
    ),
    CarModel(
      "Wartburg",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/wartburg.png",
      "hard",
    ),
    CarModel(
      "Weltmeister",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/weltmeister.png",
      "hard",
    ),
    CarModel(
      "Western Star",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/western-star.png",
      "medium",
    ),
    CarModel(
      "Westfield",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/westfield.png",
      "hard",
    ),
    CarModel(
      "WEY",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/wey.png",
      "hard",
    ),
    CarModel(
      "Wiesmann",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/wiesmann.png",
      "hard",
    ),
    CarModel(
      "Willys-Overland",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/willys-overland.png",
      "hard",
    ),
    CarModel(
      "Workhorse",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/workhorse.png",
      "hard",
    ),
    CarModel(
      "Wuling",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/wuling.png",
      "medium",
    ),
    CarModel(
      "XPeng",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/xpeng.png",
      "easy",
    ),
    CarModel(
      "Yulon",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/yulon.png",
      "hard",
    ),
    CarModel(
      "Yutong",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/yutong.png",
      "hard",
    ),
    CarModel(
      "Zarooq Motors",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zarooq-motors.png",
      "hard",
    ),
    CarModel(
      "Zastava",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zastava.png",
      "hard",
    ),
    CarModel(
      "ZAZ",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zaz.png",
      "hard",
    ),
    CarModel(
      "Zeekr",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zeekr.png",
      "medium",
    ),
    CarModel(
      "Zenos",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zenos.png",
      "hard",
    ),
    CarModel(
      "Zenvo",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zenvo.png",
      "easy",
    ),
    CarModel(
      "Zhongtong",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zhongtong.png",
      "hard",
    ),
    CarModel(
      "Zinoro",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zinoro.png",
      "hard",
    ),
    CarModel(
      "Zotye",
      "https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zotye.png",
      "medium",
    ),
  ];
}
